# Generated by Django 4.2.15 on 2025-01-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_postimage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='post',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
