# Generated by Django 4.2.15 on 2025-01-29 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_location_post_location_name_remove_post_image_and_more'),
    ]

    operations = [
    ]
