# Generated by Django 4.2.15 on 2025-01-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_location_post_location_name_post_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location_name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
