# Generated by Django 4.2.15 on 2025-02-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
