# Generated by Django 4.2.15 on 2025-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_gallerypic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.location'),
        ),
    ]
