# Generated by Django 4.2.15 on 2025-02-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_comment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile',
        ),
    ]
